platform :ios, '8.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'HbTest' do

pod 'ReactiveCocoa'
pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'HbGoodsDetail'
pod 'HbGoodsDetailBusinessCategory'

end
